/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Window.java
 *
 * Created on Sep 20, 2012, 8:22:42 AM
 */
package masterdegree.mac.session7;

import java.awt.event.ActionEvent;
import java.io.File;

/**
 * Clase generaora de ventanas de de busqueda de archivos.
 * @author Angel_Banuelos
 */
public class Window extends javax.swing.JDialog {

    private String strDirectory;
    private String lastPath = ".";//Excecution Path

    public String getStrDirectory() {
        return strDirectory;
    }

    public void setStrDirectory(String strDirectory) {
        this.strDirectory = strDirectory;
    }

    private void init() {
        this.setLocationRelativeTo(null);
        switch (type) {
            case OPENFILE:
                jFileChooser1.setApproveButtonText("Open File");
                jFileChooser1.setDialogTitle("Select a File");

                break;
            case SAVE:
                jFileChooser1.setApproveButtonText("Save");
                jFileChooser1.setDialogTitle("Select a Folder for Save File");
                break;
            case OPENFOLDER:
                jFileChooser1.setApproveButtonText("Open Folder");
                jFileChooser1.setDialogTitle("Select a Folder");
                break;
        }
        lastPath = ".";
        jFileChooser1.setCurrentDirectory(new File(lastPath));

    }

    public enum Type {

        OPENFILE,
        SAVE,
        OPENFOLDER
    }
    private Type type;

    /**
     * Creates new form Window
     */
    public Window(java.awt.Frame parent, boolean modal, Type type) {
        super(parent, modal);
        this.type = type;

        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jFileChooser1.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });
        getContentPane().add(jFileChooser1, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
        // TODO add your handling code here:
        action(evt);
    }//GEN-LAST:event_jFileChooser1ActionPerformed
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser1;
    // End of variables declaration//GEN-END:variables

    private void action(ActionEvent evt) {
        String uka = evt.getActionCommand();
        if (evt.getActionCommand().contains("CancelSelection")) {
            this.dispose();
        } else if (evt.getActionCommand().contains("ApproveSelection")) {
            File directory = jFileChooser1.getSelectedFile();
            strDirectory = directory.getAbsolutePath();
            lastPath = directory.getPath();
            this.setVisible(false);
        }
    }
}
